# Core module for mesh operations
from core.stl_loader import (
    STLLoader,
    load_stl_file,
    LoadResult,
    ValidationError,
    validate_stl_path,
)
from core.mesh_analysis import (
    MeshAnalyzer,
    MeshDiagnostics,
    BoundingBox,
    compute_height_field,
    build_vertex_neighbors,
    build_face_neighbors,
)
from core.mesh_repair import (
    MeshRepairer,
    MeshRepairResult,
    RepairMethod,
    RepairContext,
    is_meshlib_available,
    trimesh_to_meshlib,
    meshlib_to_trimesh,
)
from core.parting_direction import (
    find_parting_directions,
    compute_visibility_paint,
    get_face_colors,
    PartingDirectionResult,
    VisibilityPaintData,
    DirectionScore,
    MeshTriangleData,
    fibonacci_sphere,
    extract_triangle_data,
    PAINT_COLORS,
    MIN_ANGLE_DEGREES,
    MIN_ANGLE_COS,
    PAIR_SELECTION_TOP_K,
)
from core.pouring_direction import (
    PouringDirectionResult as PouringDirResult,
    PersistencePair,
    evaluate_candidate_directions,
    score_pouring_direction,
    compute_persistence_pairs,
    find_mold_aware_pouring_directions,
    MoldAwarePouringDirections,
)
from core.inflated_hull import (
    generate_inflated_hull,
    compute_default_offset,
    compute_bounding_box_diagonal,
    compute_smooth_vertex_normals,
    validate_manifold,
    validate_input_mesh,
    validate_offset,
    inflate_vertices,
    subdivide_mesh,
    InflatedHullResult,
    ManifoldValidation,
    HullGenerationError,
    DEFAULT_INFLATION_PERCENT,
    DEFAULT_SUBDIVISION_ITERATIONS,
    GPU_FACE_THRESHOLD,
)
from core.mold_half_classification import (
    classify_mold_halves,
    MoldHalfClassificationResult,
    # Constants (Paper Section 4.1)
    STRONG_ALIGNMENT_THRESHOLD,
    DEFAULT_BOUNDARY_ZONE_THRESHOLD,
    PAPER_BOUNDARY_ZONE_THRESHOLD,
    ORPHAN_REGION_AREA_THRESHOLD,
)
from core.tetrahedral_mesh import (
    generate_tetrahedral_mesh,
    tetrahedralize_mesh,
    classify_tetrahedra,
    filter_tetrahedra_outside_part,
    extract_edges,
    extract_boundary_surface,
    compute_edge_lengths,
    compute_distances_to_mesh,
    build_vertex_adjacency,
    build_edge_index_map,
    prepare_parting_surface_data,
    build_edge_to_index_map,
    build_tet_edge_indices,
    compute_cut_edge_flags,
    # Edge weight functions (Paper Section 4.5)
    compute_edge_weights_simple,
    compute_edge_boundary_labels,
    # Dijkstra and primary cut functions (Paper Section 4.5)
    run_dijkstra_escape_labeling,
    compute_primary_cut_edges,
    propagate_vertex_labels,
    smooth_vertex_labels,
    filter_small_label_components,
    detect_and_eliminate_tet_pockets,
    break_cut_edge_loops,
    build_vertex_adjacency_dict,
    TetrahedralMeshResult,
    PYTETWILD_AVAILABLE,
    # Constants (Paper Section 4)
    EDGE_WEIGHT_EPSILON,
    DEFAULT_EDGE_LENGTH_FAC,
    BOUNDARY_ZONE_THRESHOLD,
    GPU_DISTANCE_FACE_THRESHOLD,
    GPU_DISTANCE_BATCH_SIZE,
    # Label smoothing constants (Tunnel Prevention)
    LABEL_SMOOTH_ITERATIONS,
    LABEL_SMOOTH_THRESHOLD,
    MIN_COMPONENT_SIZE_ABSOLUTE,
    MIN_COMPONENT_SIZE_FRACTION,
    MIN_TET_COMPONENT_SIZE_ABSOLUTE,
    MIN_TET_COMPONENT_SIZE_FRACTION,
    MAX_CUT_VALENCE,
    MAX_LABEL_PROPAGATION_ITERATIONS,
)
from core.parting_surface import (
    extract_parting_surface,
    extract_parting_surface_from_tet_result,
    smooth_parting_surface,
    repair_parting_surface,
    remove_small_boundary_loops,
    remove_small_islands,
    close_parting_surface_gaps,
    PartingSurfaceResult,
    SmallHoleRemovalResult,
    GapClosingResult,
    MARCHING_TET_TABLE,
    TET_EDGES,
    # Cut point placement constants (Paper Section 4.3)
    CUT_POINT_INTERPOLATION_MIN_T,
    CUT_POINT_INTERPOLATION_MAX_T,
    VERTEX_MERGE_EPSILON,
    # Boundary type codes for vertex classification
    BOUNDARY_TYPE_PART,
    BOUNDARY_TYPE_INTERIOR,
    BOUNDARY_TYPE_H1,
    BOUNDARY_TYPE_H2,
    BOUNDARY_TYPE_PRIMARY_JUNCTION,
    BOUNDARY_TYPE_PRIMARY_THEN_PART,
)
from core.secondary_membrane import (
    classify_secondary_membranes_by_mold_half,
    compute_secondary_vertex_labels_with_primary_awareness,
    compute_extended_secondary_cut_flags_improved,
    find_primary_adjacent_edges_in_secondary_tets,
    find_orphan_primary_cut_edges,
    find_all_unused_primary_edges,
    analyze_orphan_edges_for_secondary,
    find_orphan_edge_clusters,
    create_enhanced_secondary_cut_edges,
    SecondaryMembraneInfo,
)
from core.mold_fabrication import (
    create_outer_shell_hull,
    create_outer_collar_extension,
    extend_membrane_height,
    OuterShellHullResult,
    OuterCollarResult,
)
from core.registration_marks import (
    apply_registration_noise,
    SinusoidalRegistrationResult,
)
from core.resin_channels import (
    ResinChannelResult,
)
from core.export_artifacts import (
    export_artifacts,
    compute_volume_metadata,
    generate_metadata_text,
    ExportArtifact,
    VolumeMetadata,
    ExportResult,
)

__all__ = [
    # STL Loading
    'STLLoader',
    'load_stl_file',
    'LoadResult',
    'ValidationError',
    'validate_stl_path',
    # Mesh Analysis
    'MeshAnalyzer',
    'MeshDiagnostics',
    'BoundingBox',
    'compute_height_field',
    'build_vertex_neighbors',
    'build_face_neighbors',
    # Mesh Repair
    'MeshRepairer',
    'MeshRepairResult',
    'RepairMethod',
    'RepairContext',
    'is_meshlib_available',
    'trimesh_to_meshlib',
    'meshlib_to_trimesh',
    # Parting direction
    'find_parting_directions',
    'compute_visibility_paint',
    'get_face_colors',
    'PartingDirectionResult',
    'VisibilityPaintData',
    # Pouring direction
    'find_mold_aware_pouring_directions',
    'MoldAwarePouringDirections',
    'PouringDirResult',
    'PersistencePair',
    'evaluate_candidate_directions',
    'score_pouring_direction',
    'compute_persistence_pairs',
    # Inflated hull
    'generate_inflated_hull',
    'compute_default_offset',
    'compute_smooth_vertex_normals',
    'validate_manifold',
    'InflatedHullResult',
    'ManifoldValidation',
    # Mold half classification
    'classify_mold_halves',
    'MoldHalfClassificationResult',
    # Tetrahedral mesh
    'generate_tetrahedral_mesh',
    'tetrahedralize_mesh',
    'extract_edges',
    'compute_edge_lengths',
    'compute_distances_to_mesh',
    'build_vertex_adjacency',
    'build_edge_index_map',
    'prepare_parting_surface_data',
    'build_edge_to_index_map',
    'build_tet_edge_indices',
    'compute_cut_edge_flags',
    'TetrahedralMeshResult',
    'PYTETWILD_AVAILABLE',
    # Parting surface extraction
    'extract_parting_surface',
    'extract_parting_surface_from_tet_result',
    'smooth_parting_surface',
    'repair_parting_surface',
    'remove_small_boundary_loops',
    'remove_small_islands',
    'close_parting_surface_gaps',
    'PartingSurfaceResult',
    'SmallHoleRemovalResult',
    'GapClosingResult',
    'MARCHING_TET_TABLE',
    'TET_EDGES',
    # Secondary membrane
    'classify_secondary_membranes_by_mold_half',
    'compute_secondary_vertex_labels_with_primary_awareness',
    'compute_extended_secondary_cut_flags_improved',
    'find_primary_adjacent_edges_in_secondary_tets',
    'find_orphan_primary_cut_edges',
    'find_all_unused_primary_edges',
    'analyze_orphan_edges_for_secondary',
    'find_orphan_edge_clusters',
    'create_enhanced_secondary_cut_edges',
    'SecondaryMembraneInfo',
    # Mold fabrication (hard shell)
    'create_outer_shell_hull',
    'create_outer_collar_extension',
    'extend_membrane_height',
    'OuterShellHullResult',
    'OuterCollarResult',
    # Registration marks
    'apply_registration_noise',
    'SinusoidalRegistrationResult',
    # Resin channels
    'ResinChannelResult',
    # Export artifacts
    'export_artifacts',
    'compute_volume_metadata',
    'generate_metadata_text',
    'ExportArtifact',
    'VolumeMetadata',
    'ExportResult',
]

